### ISSUE TITLE
Not really a bug, but the program doesn't tell you what it needs correctly.

### ISSUE THREAD

**Issue by whitetxt** [JeeZeh/steam-shortcut-generator#2]
From looking through the code, you are using the "ResolveVanityURL" area of the Steam API to get a user's ID.
This API call requires the custom vanity url that can be set through the steam settings.
Your program requests you enter your username, which then promptly returns the error "Could not retrieve SteamID from username. Double check your username and try again".
This happens even if you havent set a custom link.
Ultimately, what i'm saying is that your program incorrectly reports what you need to enter.

**Comment by jesse-ashmore** [comment]
I see. I completely forgot that the vanity URL could he changed. I will update it to specify this is what I'm looking for from the user.

What do you mean by it happens even without setting a custom link? If you could, please provide me the input which produces an error

**Comment by whitetxt** [comment]
So if the user hasn't set their custom vanity URL (e.g its still https://steamcommunity.com/profiles/12345678901234567), I believe it is impossible to get their steamid from the ResolveVanityURL.
You can try it with this profile https://steamcommunity.com/profiles/76561198353396836
Entering their username or steamid from the URL doesn't work.

**Comment by jesse-ashmore** [comment]
Thanks for clarifying all that!

I've looked into it and it seems this is a downfall of the Steam API. I couldn't find any other suitable method, besides scraping, to get a Steam ID from a username without checking against their vanity URL.

I've just pushed an update that clarifies, hopefully a little better, what's being asked. Additionally, you can now manually enter a Steam ID instead of a username.  So, the profile you linked should now work if you enter the ID (76561198353396836) manually. An edge case here is if someone happens to have a username that matches the steam ID you entered, as I always try to resolve what you enter as a username first.

I've also tried to improve some of the error handling and explanations when things go wrong.

**Comment by whitetxt** [comment]
Ah ok, if the Steam API doesn't support that then its understandable why you have done it this way.

**Comment by kotx** [comment]
You could also get the steam id from C:\Program Files (x86)\Steam\config\loginusers.vdf.
Also surely you could get the list of installed games locally? I'm not sure why we need to query the user's game library.

**Comment by jesse-ashmore** [comment]
> You could also get the steam id from C:\Program Files (x86)\Steam\config\loginusers.vdf.

Nice idea, thanks, will work on this!

> I'm not sure why we need to query the user's game library

IIRC, the URL for a given app icon can't be determined from the local library files/indexes alone, we need to query the Steam API for either:
1. The user's full library, which includes per-app metadata
2. An API call to pull metadata for each app ID found locally

We could rely entirely on local data for library info, but we'd still need to retrieve the app ID as per (2).
